apiVersion: apps/v1
kind: Deployment
metadata:
  name: murmur-deployment
  labels:
    app: murmur
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: murmur
  template:
    metadata:
      labels:
        app: murmur
    spec:
      securityContext:
        fsGroup: 1337
      containers:
      - image: samlockart/murmur:1.3.4
        imagePullPolicy: Always
        name: murmur-container
        stdin: true 
        tty: true 
        ports:
        # gRPC
        - containerPort: 5005
        # UDP/TCP murmur
        - containerPort: 64738
        readinessProbe:
          tcpSocket:
            port: 64738
          initialDelaySeconds: 5
          periodSeconds: 0
        livenessProbe:
          tcpSocket:
            port: 64738
          initialDelaySeconds: 300
          periodSeconds: 0
        volumeMounts:
        - mountPath: /murmurtmp
          name: murmur-folder
        - mountPath: /murmur/ssl
          name: murmur-tls
        - mountPath: /murmur/db
          name: murmur-db
        - mountPath: /murmur/murmur.ini
          name: murmur-config
          subPath: murmur.ini
        securityContext:
          runAsUser: 1337
          readOnlyRootFilesystem: true
          runAsNonRoot: true
      volumes:
      - name: murmur-folder
        emptyDir: {}
      - name: murmur-tls
        secret:
          secretName: murmur-tls
      - name: murmur-db
        persistentVolumeClaim:
          claimName: murmur-db
      - name: murmur-config
        configMap:
          name: murmur-config
