apiVersion: apps/v
kind: Deployment
metadata:
  name: murmur-deployment
  labels:
    app: murmur
spec:
  selector:
    matchLabels:
      app: murmur
  template:
    metadata:
      labels:
        app: murmur
    spec:
      containers:
      - image: samlockart/murmur:.3.4
        imagePullPolicy: Always
        name: murmur-container
        stdin: true 
        tty: true 
        ports:
        # gRPC
        - containerPort: 5005
        # UDP/TCP murmur
        - containerPort: 64738
        readinessProbe:
          tcpSocket:
            port: 64738
          initialDelaySeconds: 5
          periodSeconds: 0
        livenessProbe:
          tcpSocket:
            port: 64738
          initialDelaySeconds: 300
          periodSeconds: 0
        volumeMounts:
        - mountPath: /murmur
          name: murmur-folder
        - mountPath: /murmur/ssl
          name: murmur-ssl
        - mountPath: /murmur/db
          name: murmur-db
        - mountPath: /murmur/murmur.ini
          name: murmur-config
          subPath: murmur.ini
        securityContext:
          runAsUser: 9
          readOnlyRootFilesystem: true
          runAsNonRoot: true
      volumes:
      - name: murmur-folder
        emptyDir: {}
      - name: murmur-ssl
        secret:
          secretName: murmur-ssl
      - name: murmur-db
        persistentVolumeClaim:
          claimName: murmur-db
      - name: murmur-config
        configMap:
          name: murmur-config
