apiVersion: v1
kind: Service
metadata:
  name: murmur-service-udp
  annotations:
    metallb.universe.tf/allow-shared-ip: murmur
  labels:
    app: murmur
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: murmur-udp
      port: 64738
      protocol: UDP
  selector:
    app: murmur
---
apiVersion: v1
kind: Service
metadata:
  name: murmur-service-tcp
  annotations:
    metallb.universe.tf/allow-shared-ip: murmur
  labels:
    app: murmur
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: murmur-tcp
      port: 64738
      protocol: TCP
  selector:
    app: murmur
---
apiVersion: v1
kind: Service
metadata:
  name: murmur-service-grpc-tcp
  labels:
    app: murmur
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
    - name: murmur-grpc-tcp
      port: 50051
      protocol: TCP
  selector:
    app: murmur
