apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- 00-murmur-namespace.yaml
- 05-murmur-pvc.yaml
- 10-murmur-deployment.yaml
- 15-murmur-configmap.yaml
- 20-murmur-svc.yaml
- 30-murmur-tls.yaml

namespace: mumble

images:
  - name: samlockart/murmur
    newTag: 1.3.4
